services:
  # app:
  #   build: .
  #   container_name: ana_conta_corrente
  #   environment:
  #     - ORACLE_HOST=oracle-db
  #     - ORACLE_PORT=1521
  #     - ORACLE_USER=system
  #     - ORACLE_PASSWORD=oracle
  #     - ORACLE_SERVICE=free
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - oracle-db

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      - ORACLE_PASSWORD=oracle
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data:
